services:
    backend:
        build: .
        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"
        depends_on:
            - db
        environment:
            - DB_PORT=${POSTGRES_PORT}
            - DB_USER=${POSTGRES_USER}
            - DB_PASSWORD=${POSTGRES_PASSWORD}
            - DB_NAME=${POSTGRES_NAME}
            - DB_HOST=${POSTGRES_HOST}
            - ACCESS_KEY=${ACCESS_KEY}
            - WEATHERSTACK_URL=${WEATHERSTACK_URL}
        volumes:
            - .:/app
            - /app/node_modules

    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_NAME}
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./initdb:/docker-entrypoint-initdb.d

volumes:
    postgres-data:
